### ISSUE TITLE
Dashboard slows down and some cards no longer work properly

### ISSUE THREAD

**Issue by pluusla** [Nerwyn/material-you-theme#49]
**Checklist:**

-   [X] I updated to the latest version available
-   [X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
Unknown, the problem has existed for a while

HA-info:
Core 2024.12.0
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.4

**Browser and Operating System:**
Brave (v1.73.97) , Firefox / Windows, Android

**Description of problem:**
First of all, I would like to thank you for the great theme. I know that a lot of work has gone into it. I am an absolute fan of it and would like to continue using it.

Now to my problem:
I have noticed that there have been problems for some time (I can't say exactly when).

I use the theme with all mods. In addition to the standard cards, I also use mushroom and bubble cards in my dashboard.

For some time now I have noticed that the dashboard in the browser on the PC as well as in the mobile app becomes sluggish and slow after a certain time. This means that certain functions no longer work, e.g. closing bubble cards (if a pop-up has been opened)

Card mod is installed and correctly stored as a resource. I have tried Card-Mod versions 3.4.0 to 3.4.3 individually. The problem exists with all versions.
I do not use any other card mod customizations apart from the theme itself.

Interestingly, the problem does not occur when I use the theme with No-Mod. For me, this actually indicates a problem with Card-Mod itself.

I realize that if this is a Card-Mod problem, no solution can be worked out here. But perhaps other users have had similar experiences.

I have also placed the problem with Card-Mod myself: https://github.com/thomasloven/lovelace-card-mod/issues/413#issuecomment-2479015104

**Javascript errors shown in the web inspector (if applicable):**

I notice a lot of memory consumption here too:
![image](https://github.com/user-attachments/assets/cefe1bef-dafb-42ec-86cb-50a2b42644cc)

As well as in the browser console after some time (when tab is open) the following error messages:
![image](https://github.com/user-attachments/assets/7bb3feb9-f846-42eb-85e0-15a70801ebe5)

`Uncaught (in promise) {code: 'not_found', message: 'Subscription not found.'} card-mod.js:1 Uncaught (in promise)  y @ card-mod.js:1 s @ card-mod.js:1 
`
After a certain time, the dashboard becomes slow and some functions, such as closing the bubble card pop-up, no longer work.

**Comment by Nerwyn** [comment]
I can't say I'm experiencing this issue or that it's related to this theme in particular. I wonder if it's related to Home Assistant closing it's connection to the browser on inactivity. Can you go to [profile settings](http://homeassistant.local:8123/profile/general), scroll down to `Browser Settings`, and disable `Automatically close connection`?

![image](https://github.com/user-attachments/assets/75fff595-9754-4313-ba85-272728897090)

**Comment by iamthekings5** [comment]
@pluusla I want to pop in and say I have the same issue, the ram usage of my browser tab gradually increases over time especially if I interact with anything card-mod related. Sometimes it goes up to 4 - 5 GB ram usage and it becomes exactly as you describe where everything is sluggish. I resolve the issue by closing the browser tab, but it doesn't solve the issue in the long term.

I have tried uninstalling card-mod and the issue was resolved, but card-mod is very useful for me and I do need it.

Is there anyone using card-mod and doesn't experience this issue?

**Comment by TioBundy** [comment]
I have the same problem, I have to go back to the default theme, however, on the web everything works fine, I don't spend much time on the web version usually, but in the apps the performance is terrible. I even deleted the data of the HA app on my Pixel 7 and it still happens (it was solved for a short time).

**Comment by TioBundy** [comment]
> [@pluusla](https://github.com/pluusla)Quiero comentar que tengo el mismo problema. El uso de RAM de la pestaña de mi navegador aumenta gradualmente con el tiempo, especialmente si interactúo con cualquier cosa relacionada con la modificación de la tarjeta. A veces, el uso de RAM llega a 4 o 5 GB y se vuelve exactamente como lo describiste, donde todo se vuelve lento. Resuelvo el problema cerrando la pestaña del navegador, pero no lo soluciona a largo plazo.
> 
> Intenté desinstalar card-mod y el problema se resolvió, pero card-mod es muy útil para mí y lo necesito.
> 
> ¿Hay alguien que use card-mod y no experimente este problema?

Personally I use Card-mod and Mushroom Rounded, maybe the problem is there. I have done thousands of tests, situations, uninstalled everything that could cause problems, such as other themes or mods, and I'm still the same. I don't dare to uninstall mushroom and Card-mod in case I lose some cards that are modified with Yaml, which cost me many hours to put them in place and make them work for all devices.

Please, @Nerwyn, could you look into these problems, we would be eternally grateful since we love your theme.

**Comment by Nerwyn** [comment]
As I've already said and the OP pointed out in their original post, this is an issue (likely a memory or undefined object one) with card-mod and not this theme in particular. Y'all need to push for a fix over there, as there's nothing I can do about it here.

**Comment by TioBundy** [comment]
> Como ya dije y el OP señaló en su publicación original, este es un problema (probablemente de memoria o de objeto indefinido) con la modificación de la tarjeta y no con este tema en particular. Deben presionar para que se solucione, ya que no hay nada que pueda hacer al respecto aquí.

You mean pressing app support from HA/Nabu Casa?, or Google if you have problems in the browser?By the way, today I was playing things on the web, and everything was frozen too.

**Comment by Nerwyn** [comment]
Are any of y'all using the color theming JS module? Does disabling/removing that make a difference? I'm refactoring some of it's logic but I don't know if it's related to this issue.

**Comment by iamthekings5** [comment]
> Are any of y'all using the color theming JS module? Does disabling/removing that make a difference? I'm refactoring some of it's logic but I don't think/know if it's related to this issue.

I am using the colour theming JS module but I'd like to point out that way before the Colour You remake I was already experiencing issues with card-mod and memory leaks. I don't think this has anything to do with your project but cannot say so with 100% certainty.

**Comment by Nerwyn** [comment]
[3.0.6](https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.6) adds some improvements to the JS module. While I don't think it'll affect y'all's performance issues as they're largely related to card-mod it's worth a shot. Make sure to clear cache and hard reset your browsers (and/or download the latest copy of the JS module if you're using a local copy) to make sure it uses the latest version.

**Comment by TioBundy** [comment]
> [3.0.6](https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.6) adds some improvements to the JS module. While I don't think it'll affect y'all's performance issues as they're largely related to card-mod it's worth a shot. Make sure to clear cache and hard reset your browsers (and/or download the latest copy of the JS module if you're using a local copy) to make sure it uses the latest version.

Version 3.0.6 is 2 weeks old now or am I looking at the wrong file?

**Comment by TioBundy** [comment]
In my case it doesn't work either, it's a shame.

**Comment by ekutner** [comment]
Same problem here. I really love the look of this theme but it very often becomes too slow to use and requires a browser page refresh to become usable again. I'm using the JS module with Firefox on my desktop and the mobile Android app, which I believe is using a chromium based webview, and the problem is happening on both. I'm not a JS developer but will happily do any debugging procedures you can suggest.

**Comment by Nerwyn** [comment]
Does the issue still happen without the JS Material Color module? What about the no-mod versions of the theme? I'm pretty sure it's an issue with card-mod which is why it isn't fixable here.

**Comment by ekutner** [comment]
It does happen with the "no mod" themes. 
I removed the module loading from the extra_module_url section of configuration.yaml and restarted HA but I see that the page is still loading it, so I'm not sure how you'd like me to try without it.
Note that the issue doesn't even require any interaction to occur. It's enough to leave a tab open on a HA dashboard and after a few hours it's stuck.

**Comment by Nerwyn** [comment]
Did you also remove it from [the lovelace resources list](http://homeassistant.local:8123/config/lovelace/resources) if present?

You're the first person to report that the issue is happening without card-mod, which is concerning. Are you changing colors a lot? The script should only trigger on page load and in certain scenarios that would require color updates. Even then it shouldn't be retaining any of the color theme information in memory to cause a memory leak. If it's happening in browser, can you open your browser dev tools console (CTRL + SHIFT + I) and see if there are any logs related to `material-roundde-theme.js`? Whether it's error logs or way more colors updated/removed logs than expected.

**Comment by ekutner** [comment]
I didn't remove it from the resource list. Now I did and will try to do a more "scientific" test and report back my findings.

**Comment by link6155** [comment]
Disabling this theme made my dashboard more responsive and saw this issue. I tried removing card-mod and it seems to have fixed the issue for me, but I will keep an eye out and report back if it pops up again.

**Comment by Nerwyn** [comment]
@link6155 let me know if you see any weird browser console logs when using this theme to help us diagnose what exactly is going on.

**Comment by ekutner** [comment]
I've now completed a more rigorous test. I removed the module and ran for a couple of days with the regular theme and the "no mod" theme all while looking for the dreaded slowness and while monitoring the resource usage with Firefox's internal process manager (about:processes).
I can confirm that when running with the "no mod" theme I was unable to reproduce the slowness and resource usage was around 500MB memory and very low CPU most of the time. It would some times just to higher number but would eventually come down to that range, which is totally normal.
When using the regular theme memory usage would gradually creep towards the 2GB mark and CPU would get to high numbers between 20-110% (I know it's more than 100% but that's what the process manager shows). The interesting thing is that I it would reproduce without doing anything. I could just leave my dashboard open for a day and it when I would get back to it it would be in the "slow" state. This suggests to me that the regular Home Assistant state updates are enough to cause this to happen, it doesn't require a lot of navigations between pages. I didn't notice anything weird in the JS console. 

I should also point out that my own dashboard is using the card_mod card quite a lot and that by itself doesn't seem to cause the problem.

**Comment by Nerwyn** [comment]
Try the latest beta (3.1.1-beta.007 at time of writing). I pre-rendered the view count jinja2 template to take that load off of card-mod. While it will reduce what card-mod is doing I don't know if it is negligible or significant on devices experience the card-mod memory leak.

**Comment by ekutner** [comment]
I will try both the beta and report also in the card-mod issues but as a developer myself I doubt the developer of the card mod will be able to make anything of it, considering the issue is not pin-pointed or easily reproducible. One thing that might be very useful, but may also be a lot of work, is to break down the theme's usage of card-mod to a finer resolution. Not just a theme with and without the mod but specific usages of the mod, for example, just the repositioning of the top dashboard toolbar to the bottom. This will allow users who are experiencing this issue to pin point exactly which usage is causing the issue and will hopefully increase the chances of the issue getting fixed.

**Comment by Nerwyn** [comment]
The theme YAML file is compiled from many source YAML and CSS files using [a build pipeline](https://github.com/Nerwyn/material-rounded-theme/blob/dev/githooks/pre-commit.py). If you want you can try selectively disabling things in the build pipeline or source files to see if anything makes a difference.

**Comment by TioBundy** [comment]
I've seen that you made several changes recently, in case you're interested in the problem, it hasn't been fixed, also a bit because of the recent Haos updates. I have tried on the phone with the app official and there were even problems of freezing the app earlier than expected. 🥲

**Comment by Nerwyn** [comment]
If I make any changes that I think might fix this I'll let y'all know here. I can't reproduce it on even my most low end nigh unusable devices so I can't do anything about it yet.

Someone who is experiencing the issue and can pinpoint the reason why has to tell me what the cause is.

**Comment by TioBundy** [comment]
Without a doubt, Card Mod has something to do with it, but I don't know if everything or activates a trigger for all this to be done. 

I can send you some card that I use with Card Mod if you want to try or try to use a card or stack of them with Card Mod, it will probably happen that way, but as I say I'm not sure either.
If I disable Card Mod at least the problems stopped, but I have too much cards and entities with that plugin to get rid of easy or look for a similar alternative.

Thanks for the job.

**Comment by ekutner** [comment]
> Someone who is experiencing the issue and can pinpoint the reason why has to tell me what the cause is.

I've started with the process of removing parts of the theme to try to pinpoint it. I didn't build it but just edited the "Material Rounded" entry in the theme's YAML file to remove all the "card-mod" entries except the following:
card-mod-root-yaml
card-mod-theme
card-mod-view-yaml

With these removals I can pretty confidently say that the issue isn't happening. I will now start bringing back some of the removed sections to try to identify which one is causing the problem, however it is a slow process because it requires quite some time to be able to say with confidence that it's not happening. Unfortunately I will have very little time in the coming 3-4 weeks so not sure how much progress I'll be able to make with it.  

> I cannot reproduce it on even my most low end nigh unusable devices so I cannot do anything about it, yet.

If I had to guess I'd say it's probably some conflict with another custom card, not related to the machine strength.

**Comment by Nerwyn** [comment]
Without `card-mod-theme` the card-mod styles won't be applied, so it makes sense that the issue doesn't happen without that field 🙃.

**Comment by Nerwyn** [comment]
> I can send you some card that I use with Card Mod if you want to try or try to use a card or stack of them with Card Mod, it will probably happen that way, but as I say I'm not sure either.

That could be helpful.

**Comment by ekutner** [comment]
> Without `card-mod-theme` the card-mod styles won't be applied, so it makes sense that the issue doesn't happen without that field 🙃.

actually, that was one of the three the I kept. The list is of those I didn't remove and I see that the views toolbar is moved from the top to the bottom of the dashboard (which is probably my favorite part of this theme and the reason I decided to start with leaving just that).

**Comment by TioBundy** [comment]
> > Puedo enviarte alguna carta que uso con Card Mod si quieres probar o intentar usar una carta o pila de ellas con Card Mod, probablemente suceda de esa manera, pero como digo tampoco estoy seguro.
> 
> Eso podría ser útil.

```

type: custom:stack-in-card
cards:
  - type: custom:mushroom-template-card
    primary: Salón
    secondary: >-
      {{ states('sensor.termometro_salon_temperature') | round (1) }}ºC | {{
      states('sensor.termometro_salon_humidity') | int }}%
    icon: ""
    card_mod:
      style: |
        ha-card {
          border: 0px;
        }
    tap_action:
      action: none
  - type: custom:mushroom-template-card
    primary: ""
    secondary: ""
    icon: mdi:sofa
    icon_color: red
    tap_action:
      action: none
    card_mod:
      style: |
        ha-card {
          border: 0px;
          --icon-size: 155px;
          margin-left: -105px;
          margin-bottom: -79px;
          margin-top: -25px;
        }
        mushroom-badge-icon {
          margin-right: 10px;
          margin-top: 10px;
          --badge-icon-size: 19px;
          --badge-size: 29px;
        }
    badge_icon: >
      {% if (states('sensor.termometro_salon_humidity') | int) >= 61 %}
      mdi:water {% elif (states('sensor.termometro_salon_temperature') | int) >=
      22.9 %} mdi:fire {% elif (states('sensor.termometro_salon_temperature') |
      int) <= 22.9 %} mdi:snowflake {% endif %}
    badge_color: |
      {% if (states('sensor.termometro_salon_humidity') | int) >= 61 %} blue
      {% elif (states('sensor.termometro_salon_temperature') | int)
      >= 22.9 %} red
      {% elif (states('sensor.termometro_salon_temperature') | int)
      <= 22.9 %} blue
      {% endif %}
  - type: custom:mushroom-template-card
    primary: ""
    secondary: ""
    layout: vertical
    icon: mdi:ceiling-light
    entity: light.luz_salon_local
    icon_color: |
      {% if (states('light.luz_salon_local')) == 'on' %} yellow {% endif %}
    card_mod:
      style: |
        ha-card {
          border: 0px;
          margin-top: -120px;
          margin-right: -120px;
          --icon-size: 45px;
        }
  - type: custom:mushroom-template-card
    primary: ""
    secondary: ""
    layout: vertical
    icon: mdi:soundbar
    entity: media_player.barra_de_sonido
    tap_action:
      action: more-info
    icon_color: |
      {% if (states('media_player.barra_de_sonido')) == 'off' %}  {% endif %}
    card_mod:
      style: |
        ha-card {
          border: 0px;
          margin-top: -80px;
          margin-right: -120px;
          --icon-size: 45px;
        }
  - type: custom:mushroom-template-card
    primary: ""
    secondary: ""
    layout: vertical
    icon: mdi:floor-lamp
    entity: light.yeelight_lampara
    icon_color: |
      {% if (states('light.yeelight_lampara')) == 'on' %} yellow {% endif %}
    card_mod:
      style: |
        ha-card {
          border: 0px;
          margin-top: -40px;
          margin-right: -120px;
          --icon-size: 45px;
        }
```

**Comment by Nerwyn** [comment]
@TioBundy thanks.

FYI [Stack In Card](https://github.com/custom-cards/stack-in-card) has not been updated since 2020. You should consider using [Vertical Stack In Card](https://github.com/ofekashery/vertical-stack-in-card) instead.

After adding about 10 of your card I saw a huge spike in memory to 1GB and 100% CPU usage, but the page was still usable and it went away after closing and reopening the page. You're using a lot of templates and they're all being cached in the frontend and sent to the backend for processing, which would explain the memory and CPU spike. Outside of that I'm not running into any usability issues.

**Comment by TioBundy** [comment]
> [@TioBundy](https://github.com/TioBundy) thanks.
> 
> FYI [Stack In Card](https://github.com/custom-cards/stack-in-card) has not been updated since 2020. You should consider using [Vertical Stack In Card](https://github.com/ofekashery/vertical-stack-in-card) instead.
> 
> After adding about 10 of your card I saw a huge spike in memory to 1GB and 100% CPU usage, but the page was still usable and it went away after closing and reopening the page. You're using a lot of templates and they're all being cached in the frontend and sent to the backend for processing, which would explain the memory and CPU spike. Outside of that I'm not running into any usability issues.

Have you used Vertical or Stack In Card for the example? I will try to make the change to vertical, yes. Well, it's strange that it doesn't happen to him, anyway to close it and reopen it, yes, but no It is practical if you try to do several things next.

However, this may only happen in certain situations with more specific factors.

**Comment by Nerwyn** [comment]
I used Stack In Card for testing, but I personally don't use either or Mushroom Cards, and have limited card-mod in my cards outside of the theme.

**Comment by Nerwyn** [comment]
I've developed an experimental alternate method of applying Material You modifications for this theme. It can be found [here](https://github.com/Nerwyn/material-rounded-theme/blob/dev/dist/material-you-theme-patcher-poc.js) in the dev branch. You can install it as a frontend extra module in configuration.yaml (I haven't tried it as just a resource but I imagine it may not work due to the tight timing it requires).

```yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/material_you_resources/material-you-theme-patcher.min.js
    - /local/material_you_resources/material-rounded-theme.js
```

In my testing the styles are applied instantaneously everywhere the modified elements appear in Home Assistant, and I'm not experiencing any card-mod related slowdowns, even minor ones. Try using it with the **No Mod** versions of the theme and let me know if you experience any performance issues.

**Comment by lnkd61** [comment]
I went ahead and added those resources and updated the theme to the dev branch. So far I am not noticing any slow downs or freezing like before. E.g. clicking outside of bubble popups would take several seconds before closing, but now it's instant.

**Comment by Nerwyn** [comment]
That's great news!

I still have a lot of work to do before this is even beta ready, so file names will change and likely so will the way that theme settings are set.

**Comment by Nerwyn** [comment]
@lnkd61 @ekutner @pluusla @pesschap @TioBundy

I've put out a beta for version four. It's a complete overhaul of how style upgrades are set and no longer uses card-mod. You'll need to uninstall the old module from frontend resources and modules, and install the new one as a frontend module and custom panel. You'll also have to re-setup your helpers, but the new configuration UI panel will make it easy. @lnkd61 gave me some positive initial feedback and it's been very snappy in my development and testing. Give it a try and let me know if y'all run into any issues with it!

https://github.com/Nerwyn/material-rounded-theme/releases/tag/4.0.0-beta.003

**Comment by deezid** [comment]
Tried to install, the bottom bar is gone which is to be expected.
But I can't download the material-you-utilities.min.js to fully enable the theme again?

**Comment by deezid** [comment]
Some feedback:
Feels faster than ever before and the material you panel works flawlessly. I really like how there's a global option for the theme but also individual ones. 
I would like some more contrast of the cards on the background itself. Since Material You they kinda blend all together. Setting the contrast to a higher value makes these slightly more visible but also adds too much contrast to other areas to me.

Another question:
Wouldn't it be possible to provide the .js file within hacs via theme updates and we just adjust the link in configuration.yaml to the theme folder?

**Comment by Nerwyn** [comment]
Glad to hear that the performance is much better!

The Material Design 3 specification has [three variants for card](https://m3.material.io/components/cards/overview), and I was mostly following the first one - elevated card. I did miss including it's elevation box shadow, which I'll add in the next beta and does help make it stand out a bit more. I tried out styling ha-cards as filled and outline cards but I still prefer elevated cards, especially after adding the elevation.

I don't think it's possible to include the JS file due to HACS limitations on themes. For themes, it only serves the theme YAML file. I can try including the JS file in the same folder.

**Comment by Nerwyn** [comment]
@deezid I've put out another beta that modifies both the theme YAML and JS module. `ha-card`s should have a box-shadow to help them pop out like described in [the specification](https://m3.material.io/components/cards/specs#a012d40d-7a5c-4b07-8740-491dec79d58b).

It turns out I can add the JS module to the themes folder and it'll be downloaded when installed through HACS. BUT for some reason it decompresses the file which undoes my webpacking and will make it load slower, and the theme folder it's downloaded to isn't publicly available and therefore can't be used to serve JS content. I'll keep the JS module in the dist folder and the current installation instructions.

**Comment by TioBundy** [comment]
Great news! I'm going to try it too to see if the problems disappear!

Thanks!

**Comment by TioBundy** [comment]
I just tried it with the mod theme, it's still happening to me, but I think you were saying to try only the No-Mod, right? With that, I'd say I've never had any problems, or at least I didn't know how to appreciate them.

The .js module has been removed from the folder you indicated. I understand that the latest beta prefers us to test by just installing the theme, or I misunderstood that part.

In short: it keeps happening to me: if I add the Mod part, which changes the tab bar at the bottom, the HA instance starts to stop responding, failing, as we already mentioned, to hold down to see more information about a card, settings, etc.; switch between tabs; change the HA area in the side panel.

**Comment by Nerwyn** [comment]
If you installed it correctly, your themes list should look something like this:

![Image](https://github.com/user-attachments/assets/741fec48-ebef-4762-b3d4-868c9bd6da33)

There should no longer be any Rounded or No Mod options. Card mod theming has been completely removed from the repository. If card-mod is still applying theme styles, then you have a caching issue or incorrect installation.

**Comment by TioBundy** [comment]
> Si lo instalaste correctamente, tu lista de temas debería verse así:
> 
> ![Image](https://github.com/user-attachments/assets/741fec48-ebef-4762-b3d4-868c9bd6da33)
> 
> Ya no debería haber opciones de Redondeado ni Sin Mod. La temática de mods de cartas se ha eliminado por completo del repositorio. Si card-mod sigue aplicando estilos de tema, significa que hay un problema de caché o una instalación incorrecta.

Well, it doesn't show it like that, and I've restarted, I have no resource in .js applied... I don't understand what happened.

**Comment by Nerwyn** [comment]
Have you thoroughly cleared cache? This sounds like a caching issue. Try uninstalling the theme YAML file completely, clearing cache, and then reinstalling the theme.

**Comment by TioBundy** [comment]
> ¿Has borrado completamente la caché? Parece que hay un problema de caché. Prueba a desinstalar el archivo YAML del tema por completo, borrar la caché y luego reinstalarlo.

I'm trying that, uninstall, force clear cache (f12 method), clean again, restart... let's see if it works now.

**Comment by Nerwyn** [comment]
Try also clearing it from the browser settings: https://its.uiowa.edu/services/how-clear-cache-and-cookies-your-web-browser#accordion-item-heading-1436

**Comment by Nerwyn** [comment]
Try using the [actions developer tool](http://homeassistant.local:8123/developer-tools/action) to run the service `frontend.reload_themes`.

**Comment by Nerwyn** [comment]
Wait `material_you` folder and `material_you.yaml`? It should still be a `material_rounded` folder `material_rounded.yaml` to prevent upgrade compatibility issues. try deleting that file, uninstalling, and reinstalling the theme from HACS.

**Comment by Nerwyn** [comment]
I just tried doing that and it installed an old version. Something is broken 😠

**Comment by Nerwyn** [comment]
Redownloading in place downloaded the correct v4 beta, so that seems to be a HACS bug. So try uninstalling the theme from HACS, refreshing, reinstalling the theme beta from HACS, and then reinstalling it again if the downloaded file contains any references to `Material Rounded` or `card-mod`.

**Comment by Nerwyn** [comment]
> But no more file for material_you or any folder with material you

That's how it should be! I briefly tried renaming the folder and file to `material_you` but the old `material_rounded` file wasn't deleted on update (another HACS issue), so I decided to keep the old file name to prevent issues like this. Thanks for being a beta tester! 🙃

**Comment by TioBundy** [comment]
> > Al volver a descargar la versión beta v4 correcta, parece que se trata de un error de HACS. Prueba a desinstalar el tema de HACS, actualizar, reinstalar la versión beta del tema desde HACS y, a continuación, reinstalarlo de nuevo si el archivo descargado contiene alguna referencia a `Material Rounded`o `card-mod`.
> 
> ¡Funcionó! Ya no veo una selección para el antiguo Material Rounded y, en \config\themes\material_rounded, simplemente tengo un archivo material_rounded.yaml. Pero ya no hay archivos para material_you ni para ninguna carpeta con material you.

I have the same thing in that folder, but I still get the whole old list of themes😩.

**Comment by Nerwyn** [comment]
@TioBundy did you open the `material_rounded.yaml` file and check to see if it still contained the old "Material Rounded" and "No Mod" versions of the theme? If it does try reinstalling the v4 beta theme from HACS again. If not try using the [actions developer tool](http://homeassistant.local:8123/developer-tools/yaml) to run the service `frontend.reload_themes`.

**Comment by Nerwyn** [comment]
FYI I've changed the theme YAML name to `material_you.yaml` and added a callout to the release notes that you should uninstall and reinstall the theme, and possibly delete the `Material Rounded` folder and YAML when updating. @TioBundy this may help with your HACS install/caching issues.

The theme and module are just about feature complete and I've completed mostly completed the README updates. I'm hoping to officially release it in a day or two and I'll close out this issue then.

**Comment by Nerwyn** [comment]
> Thank you very much! Let's see if it is possible to update it so that it is complete, how complicated.

Any updates?

> Thanks you Buddie.

😎 

> For pleasure you have tried to modify the "Dark" option of the theme for an "OLED Friendly" with absolute black of base color?, I don't know if with the modifications it is possible to create it or it would give problems.

I haven't tried setting the background to OLED black as it wouldn't be in the Material Design 3 specification, nor do I have an OLED display (I opted for a non-OLED HDR 32:9 because I didn't want VSCode, Home Assistant, GitHub, and the browser dev tools burned into my monitor from working on these projects so much 😆).

Outside of this theme, you could add a fronted resource stylesheet [as described here](https://github.com/Nerwyn/material-rounded-theme/tree/dev?tab=readme-ov-file#alternativeoptional-build-your-own-theme) that replaces `--view-background` with pure black. The CSS file would look like this:

```css
body {
    --view-background: #000000;
}
```

**Comment by TioBundy** [comment]
> > Thank you very much! Let's see if it is possible to update it so that it is complete, how complicated.
> 
> Any updates?
> 
> > Thanks you Buddie.
> 
> 😎
> 
> > For pleasure you have tried to modify the "Dark" option of the theme for an "OLED Friendly" with absolute black of base color?, I don't know if with the modifications it is possible to create it or it would give problems.
> 
> I haven't tried setting the background to OLED black as it wouldn't be in the Material Design 3 specification, nor do I have an OLED display (I opted for a non-OLED HDR 32:9 because I didn't want VSCode, Home Assistant, GitHub, and the browser dev tools burned into my monitor from working on these projects so much 😆).
> 
> Outside of this theme, you could add a fronted resource stylesheet [as described here](https://github.com/Nerwyn/material-rounded-theme/tree/dev?tab=readme-ov-file#alternativeoptional-build-your-own-theme) that replaces `--view-background` with pure black. The CSS file would look like this:
> 
> body {
>     --view-background: #000000;
> }

I wanted to say to see if the theme is fully installed as it showed and not with the old specification.

I will try that absolute black style, since the "Dark" in my opinion worsens the viewing of certain elements, cards, or icons, perhaps the greatest contrast will help everything look better.

**Comment by Nerwyn** [comment]
> I wanted to say to see if the theme is fully installed as it showed and not with the old specification.

Are the performance issues gone?

**Comment by ekutner** [comment]
I'm also starting to test the new theme as well . For now I have some observations about setting it up:
1. The CDN URL (https://cdn.jsdelivr.net/gh/nerwyn/material-rounded-theme@main/dist/material-you-utilities.min.js) doesn't work.
2. I couldn't get it to install properly with HACS. I tried removing the old theme, hard refresh+clear cache, download the v4 beta version but it still downloaded the latest v3. I had to do "re-download" and then manually delete the "material_rounded" folder.
3. The contrast control is awesome, I can finally use dark mode and get decent contrast between the background and the cards/controls.

So far the theme has been very responsive and I didn't observe and slowness but I'll give it some time and report back.

**Comment by Nerwyn** [comment]
> The CDN URL (https://cdn.jsdelivr.net/gh/nerwyn/material-rounded-theme@main/dist/material-you-utilities.min.js) doesn't work.

I forgot to clear the jsDelivr cache for that URL. My bad! It should now once you clear cache on your devices.

> I couldn't get it to install properly with HACS. I tried removing the old theme, hard refresh+clear cache, download the v4 beta version but it still downloaded the latest v3. I had to do "re-download" and then manually delete the "material_rounded" folder.

That sounds like the HACS theme pre-release version issue bug we were experiencing. I found that downloading the same pre-release twice causes it to download the correct one. I imagine this bug shouldn't occur once v4 is officially released.

> So far the beta version has been pretty responsive for me as well. One thing I've noticed is the page title for dashboards is a bit too close the edge. I am using Zen Browser 1.11.3b.

I'm guessing that's a single tab view? The page title created for single view titles is created by Home Assistant, while the one on multi-tab views is a pseudo-element of the current view tab. Single tab and subviews use the [small top app bar](https://m3.material.io/components/top-app-bar/specs#14e23895-ac2e-40d8-b0f7-8d016c10a225) specification, while multi-tab views use the [center-aligned top app bar](https://m3.material.io/components/top-app-bar/specs#51ac0fae-61c2-4abc-b8f9-1167bf54e875) specification. It looks better on mobile views where the menu button is present in the top app bar rather than the sidebar.

**Comment by Nerwyn** [comment]
Oh wait, that's the main branch URL. It isn't live yet. Try using the dev branch URL: https://cdn.jsdelivr.net/gh/nerwyn/material-rounded-theme@dev/dist/material-you-utilities.min.js. I can add a note to the README.

**Comment by Nerwyn** [comment]
@lnkd61 I've centered the headline of single tab views and fixed the fonts of it and the default subview headlines, so the match the specification and the top app bar headlines created by this theme.

**Comment by Nerwyn** [comment]
I'm starting to think that I should split this module into a separate repo to make the HACS installation and updating much easier. That way updating it through HACS would update the JS module itself. As it is now almost all updates are changes to the JS module, so users would have to update it manually every time.

**Comment by Nerwyn** [comment]
Alright I think it's all ready now. I've moved the companion JavaScript module into [its own repository](https://github.com/Nerwyn/ha-material-color-utilities). Remove the old module from your Home Assistant installation, and then add [this new repository](https://github.com/Nerwyn/ha-material-color-utilities) as a custom repository in HACS. You can then update your frontend extra module and configuration panel URLS in `configuration.yaml` to use the HACS URL and restart Home Assistant. Any future updates will be downloaded through HACS which will make it much easier for y'all.

**Comment by TioBundy** [comment]
I don't know how many times I have uninstalled the thema, cleared cache and looking that there are no remaining folders or modules somewhere in the Haos installation and I continue with the old theme listing although Install new betas, I have even put the changes inconfiguration.yamlthat you have suggested and it doesn't work either🥲.

**Comment by ekutner** [comment]
> Alright I think it's all ready now. I've moved the companion JavaScript module into [its own repository](https://github.com/Nerwyn/ha-material-color-utilities)

I've installed the script from the new repo and everything is working fine but to be honest, most people will probably be better off just using it from the CDN. I understand that the need for a separate repo is a limitation of HACS so I'd highly recommend opening a feature request there to support including a script with the theme. I can't think of a good reason why that won't be possible and it will make the setup of this great them a lot easier.

**Comment by xvlw** [comment]
So i ran through the instructions as well, after completing everything Material Rounded still was showing up as an option to select as well as its variants

When browsing the /themes/ folder I noticed that there was still a folder for material_rounded and another folder for material_you

Also inside the material_you folder there were 2 yaml files, one for material_rounded and material_you

I deleted the material_rounded folder and yaml file and deleted the material_rounded yaml from the material_you folder, rebooted HA and the options to select the material rounded theme were gone

What I am left with are these options below, should I still continue to have the variants of Material You?

![Image](https://github.com/user-attachments/assets/98d38919-5940-4b4a-a322-01a672bac826)

This is the /themes/ folder content

![Image](https://github.com/user-attachments/assets/300aedf9-8cef-446b-b61d-159b165cf596)

**Comment by TioBundy** [comment]
> So i ran through the instructions as well, after completing everything Material Rounded still was showing up as an option to select as well as its variants
> 
> When browsing the /themes/ folder I noticed that there was still a folder for material_rounded and another folder for material_you
> 
> Also inside the material_you folder there were 2 yaml files, one for material_rounded and material_you
> 
> I deleted the material_rounded folder and yaml file and deleted the material_rounded yaml from the material_you folder, rebooted HA and the options to select the material rounded theme were gone
> 
> What I am left with are these options below, should I still continue to have the variants of Material You?
> 
> ![Image](https://github.com/user-attachments/assets/98d38919-5940-4b4a-a322-01a672bac826)
> 
> This is the /themes/ folder content
> 
> ![Image](https://github.com/user-attachments/assets/ad82d1d7-3498-44ce-bdfb-79dfd35843ca)

You use Visual Studio? Perhaps the basic explorer is not able to see everything inside the folders.

**Comment by xvlw** [comment]
File Editor below as another view and matches what i see in VS 

The question i had was if the Theme Options are what i should expect to see and that even after removing Material You via HACS and reinstalling it, it left over the residual Material Rounded folder / YAML file as well as a material_rounded YAML in the material_you folder

![Image](https://github.com/user-attachments/assets/bee1bb32-0e29-4ace-be2e-c55c2f584500)

**Comment by Nerwyn** [comment]
> I've installed the script from the new repo and everything is working fine but to be honest, most people will probably be better off just using it from the CDN. I understand that the need for a separate repo is a limitation of HACS so I'd highly recommend opening a feature request there to support including a script with the theme. I can't think of a good reason why that won't be possible and it will make the setup of this great them a lot easier.

If you really want to you can install it using jsDelivr using [this URL](https://cdn.jsdelivr.net/gh/nerwyn/ha-material-color-utilities@main/dist/material-you-utilities.min.js), but I wouldn't recommend it as I won't be managing it (ensuring that jsDelivr clears its cache and ensures the module it serves is up to date) anymore. A theme with its own companion module is a niche use case (I think only LCARS theme also does so) so I doubt they'll be open to implementing support for it. At this point the module is similar to frontend modules like card-mod and it makes more sense to install it like one.

> Diving deeper, when i look through the material_you.yaml file i do see references to the options in my first screenshot Material You No Mod Material You No Mod Dark Material You Dark: ect so i'm guessing if this is the correct YAML file then the variants should still be there

The `No Mod` variants shouldn't be there, that has to be some weird HACS installation or caching issue. Try running the action `frontend.reload_themes`. I imagine that we'll get around this HACS bug installing older versions of the theme YAML once version 4 is released, as it keeps pulling the latest release initially instead of the beta.

**Comment by xvlw** [comment]
I ran `frontend.reload_themes` which didn't change anything and then I tried rebooting Home Assistant in general and I am still seeing it

![Image](https://github.com/user-attachments/assets/454ba40e-f1ef-472c-8341-7ef25dae5779)

![Image](https://github.com/user-attachments/assets/889e5701-c1a0-4097-ba44-255affa5e2b9)

Also noticing that the highlight around the bottom navigation bar has turned into a square instead of the oval

![Image](https://github.com/user-attachments/assets/e1475caa-b5b4-48eb-9192-b4dcfea85062)

It does however keep its shape in the left hand navigation window

![Image](https://github.com/user-attachments/assets/0d27ac7c-5c05-4511-a7f6-d17bb7b2ca50)

**Comment by Nerwyn** [comment]
That is not the most up to date YAML file, no. Try reinstalling the latest beta **twice**. HACS sometimes installs the latest version instead of the beta version even when installing a pre-release theme.

**Comment by xvlw** [comment]
Ok so steps should be the following:

- uninstall via HACS
- re-download 4.0.0-beta.016 via HACS
- uninstall via HACS again
- re-download 4.0.0-beta.016 via HACS

Does this line up with what you explained?

At any point should i be restarting HA?

**Comment by TioBundy** [comment]
![Image](https://github.com/user-attachments/assets/b002fc40-3414-41eb-b756-4ead59254eff)
![Image](https://github.com/user-attachments/assets/7b336c79-6b88-44d3-a1c2-999080b8f0e0)
![Image](https://github.com/user-attachments/assets/05b07943-a31e-4fcf-b06c-8aa2db71601a)

Deleting the Yaml files and the folders in /themes before deleting the theme, and installing the last beta twice, it applies partially things to me as you can see, the contrast on the cards is very Well, worthy of the changes that you have been mentioning and were made, but I don't have the side menus or anything else apparently and I still have a big list of themes modes that It still does not correspond to what it would touch to indicate a correct installation.

**Comment by TioBundy** [comment]
I've tried again to do what I say above and I'll be like before, xD. I don't try anything anymore until the theme is out of beta, let's see if my instance wants to take the full theme.

**Comment by Nerwyn** [comment]
> Does this line up with what you explained?

@xvlw Don't uninstall a second time, just reinstall it again. If you uninstall it the HACS theme install bug will cause it to install the release version again. No restarts required for installing theme. Restarting Home Assistant is only required for the JS module initial installation for the `configuration.yaml` changes. 

> Deleting the Yaml files and the folders in /themes before deleting the theme, and installing the last beta twice, it applies partially things to me as you can see, the contrast on the cards is very Well, worthy of the changes that you have been mentioning and were made, but I don't have the side menus or anything else apparently and I still have a big list of themes modes that It still does not correspond to what it would touch to indicate a correct installation.

It looks like the JS module isn't running. Do you see anything relevant in the browser logs? What does your `configuration.yaml` look like? Have you restarted since updating `configuration.yaml`?

**Comment by Nerwyn** [comment]
FYI: I've changed the module repo name to [`ha-material-you-utilities`](https://github.com/Nerwyn/ha-material-you-utilities), as its more than just color. GitHub automatically re-points repos to their new name and the old URL should continue to work with HACS if you've already installed it. You may want to uninstall and reinstall it using the new URL just to be safe. (This was also a test to see if I can safely rename my other projects already on HACS, including this theme. I apparently suck at initially naming things since all of my HACS projects have been renamed since first release).

**Comment by xvlw** [comment]
This has become a game of whack a mole haha :D

I followed your instructions, removed via HACS, re-downloaded the beta, then reinstalled the beta again. (even threw in a HA reboot for good measure)

This seems to have removed references to the Material You No Mod from the YAML file and i do notice some additional changes to the theme (very nice changes by the way)

However it also downloaded the Rounded theme again and in the theme selector the no mod version still shows even though its not in the YAML

I had also hit the `frontend.reload_themes` a few times

![Image](https://github.com/user-attachments/assets/3c0d8d61-4b18-454f-bdfd-2ec20771914b)

![Image](https://github.com/user-attachments/assets/22e64a9d-eed1-47b3-98e8-751a32a55a54)

**Comment by Nerwyn** [comment]
If you delete the `material_rounded` folder it should fix it. It shouldn't download that folder again once I release this.

**Comment by xvlw** [comment]
Bingo, looks like that did the trick

![Image](https://github.com/user-attachments/assets/c80e1040-8258-4c4f-a399-a716f11c85a4)

**Comment by xvlw** [comment]
I like it a lot

**Comment by xvlw** [comment]
> > Did this theme come with a new font?
> 
> It does if you install it! [More info in the README](https://github.com/Nerwyn/material-rounded-theme/tree/dev?tab=readme-ov-file#optional-figtree-font-installation).
> 
> A while ago a user asked if this theme could use the Product Sans font. But Product Sans is both proprietary to Google, and not optimized for non-headline use. Google Sans is optimized for regular use but is also proprietary. I tested a bunch of free fonts and found that Figtree was the most similar to Google Sans, so I added it to this themes font family priority list.

So I added the font as a resource and hit CTRL + F5

![Image](https://github.com/user-attachments/assets/027b2ec9-40ac-40a7-91f7-a25030983819)

However the bottom navigation is now sitting top left :)

![Image](https://github.com/user-attachments/assets/bead53b1-0616-4acd-9785-80969ddc4b15)

**Comment by Nerwyn** [comment]
Definitely not the font. Are your `configuration.yaml` URLs up to date?

**Comment by Nerwyn** [comment]
You may have the old repo `ha-material-color-utilities` still listed as a folder as well. Beta testing woes. It should be `ha-material-you-utilities` if you remove/re-add the repo as a custom repository.

**Comment by ekutner** [comment]
>  apparently suck at initially naming things since all of my HACS projects have been renamed since first release).

It's a well known fact that the two hardest things in computer science are distributed cache revokes and naming things :))

**Comment by Nerwyn** [comment]
At least browser cache isn't distributed 🙃

**Comment by xvlw** [comment]
I had swapped to the new utilities URL prior and deleted it from the Custom Repo section of HACS.

Viewing that list again i don't see the old repo listed in the custom repo list. Is there somewhere else the old repo could be hiding?

![Image](https://github.com/user-attachments/assets/c5ce7b50-cfaf-41f4-a250-4d69c645499a)

**Comment by xvlw** [comment]
> Definitely not the font. Are your `configuration.yaml` URLs up to date?

Crap its probably this. What should be the URL in configuration.yaml now

This is what I have currently

```
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/ha-material-color-utilities/material-you-utilities.min.js
```

![Image](https://github.com/user-attachments/assets/37914aa6-fe44-4e62-9129-e06f37ba6f11)

This is what is on the alpha branch of the repo [readme](https://github.com/Nerwyn/ha-material-you-utilities/tree/1.0.0-alpha.001)

![Image](https://github.com/user-attachments/assets/ea6717f1-1b2f-499e-b7f0-17dd68cfcf37)

**Comment by Nerwyn** [comment]
That'd do it. I haven't updated the URLs yet. Sorry! I was working on a bug fix for non-admin users.

**Comment by xvlw** [comment]
Hey no worries and no rush at all!

Send it over when you have it and I'll test again

**Comment by Nerwyn** [comment]
You should already be able to to fix it by change `-color-` to `-you` in both URLs, it's pointing to a local folder.

**Comment by xvlw** [comment]
Easy enough, looks good now

**Comment by Nerwyn** [comment]
Alright, pushed the updates to the module repo. I'm going to work on renaming this one to Material You and get things ready for release.

**Comment by xvlw** [comment]
Just checked on the companion app (android) and it looks like the bottom nav bar is top left on there

I cleared cache via system settings and relaunched the app but still stuck at the top left

**Comment by Nerwyn** [comment]
> Just checked on the companion app (android) and it looks like the bottom nav bar is top left on there
I cleared cache via system settings and relaunched the app but still stuck at the top left

That's a cache bug with the Android companion app. Someone else had run into it yesterday and make a separate bug thread for it [here](https://github.com/Nerwyn/material-rounded-theme/issues/78). The solution is to either sideload a new version of the companion app (I'm on the beta and have [this one](https://github.com/home-assistant/android/releases/tag/2025.4.1)) so you can use [the new reset frontend cache button](https://github.com/home-assistant/android/pull/5119) or to clear app data and set it back up.

**Comment by Nerwyn** [comment]
[Material You Theme 4.0.0](https://github.com/Nerwyn/material-you-theme/releases/tag/4.0.0) and [Material You Utilities 1.0.0](https://github.com/Nerwyn/ha-material-you-utilities/releases/tag/1.0.0) have been officially released! While I'll close this bug, we can keep discussing any issues we run into related to these releases here, or in new issue threads or discussions.

**Comment by xvlw** [comment]
> > Just checked on the companion app (android) and it looks like the bottom nav bar is top left on there
> > I cleared cache via system settings and relaunched the app but still stuck at the top left
> 
> That's a cache bug with the Android companion app. Someone else had run into it yesterday and make a separate bug thread for it [here](https://github.com/Nerwyn/material-rounded-theme/issues/78). The solution is to either sideload a newer pre-release version of the companion app (I'm on the beta and have [this one](https://github.com/home-assistant/android/releases/tag/2025.4.1)) so you can use [the new reset frontend cache button](https://github.com/home-assistant/android/pull/5119) or to clear app data and set it back up.

Thanks, that helped! I was able to apply for the beta from that repo and update immediately. The current beta on the play store has  the new `reset frontend cache button` and that fixed the nav bar position

**Comment by ekutner** [comment]
thank you for your great work on this theme @Nerwyn

**Comment by xvlw** [comment]
It's been about a week and performance is oh so much better. 

Thank you again for the huge effort im sure this update required.
