### ISSUE TITLE
Incompatible with 2025.5

### ISSUE THREAD

**Issue by valentinfrlch** [Nerwyn/material-you-theme#87]
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:**
latest

**Last working release (if known):**

**Browser and Operating System:**

**OS**: macOS and iOS
**Browser**: Chromium (Arc) and WebKit (Safari)

First of all, thank you for your amazing work! This theme makes Home Assistant look so much better.
After upgrading to the latest Home Assistant version (2025.5) (I'm running Home Assistant OS on a Raspberry Pi 5), the Navigation Bar breaks. I have cleared the frontend cache on iOS in the companion app settings and tried force refreshing & hard reloading the page on Chrome. The issue persists. 
I also have the Material You Utilities installed.

This is how it looks in Chrome (macOS):
<img width="683" alt="Image" src="https://github.com/user-attachments/assets/950d39c0-9caa-4689-a53e-74437fea6e0a" />

**Javascript errors shown in the web inspector (if applicable):**

```
Timeout waiting for shadowRoot in [object HTMLElement] after 60000ms. Te	@	material-you-utilities.min.js:2
```

**Additional information:**
If there is anything else I can provide, please let me know.

**Comment by Ascathon** [comment]
Tabs don't work in Firefox/Windows 11 either.
Minor issue, the notification badge in the cog isn't really visible.

**Comment by Nerwyn** [comment]
The sidebar styles are also broken. Ugh. I'll start working on a fix soon.

**Comment by Nerwyn** [comment]
![Image](https://github.com/user-attachments/assets/6c6a859f-bb96-4fa2-8577-f10e2713a1d6)

They redid the view tabs elements, which is a good sign that this is fixable.

**Comment by Nerwyn** [comment]
> I already noticed this when trying out the beta. Should I have already reported it in this case?

Yeah, but I also am not on the frontend beta. I probably should be to head off things like this.

**Comment by Nerwyn** [comment]
I've put out an alpha for Material You Utilities that fixes the view tabs, but am still working on the sidebar.

**Comment by Nerwyn** [comment]
I've put out a beta that should fix everything. If y'all want to spot check it while I work on fixes for my other projects that were broken from the changes in tabs.

**Comment by xvlw** [comment]
Having a tough time installing utilities 1.0.10-beta.002 to give it a test

I re-download the beta in HACS and it shows 1.0.10-beta.002

![Image](https://github.com/user-attachments/assets/65e8fadc-d899-47f0-b64b-66de24a6f812)

When I go to update it shows installed version is 1.0.10-beta.002 but latest version is 1.0.9

![Image](https://github.com/user-attachments/assets/7edf7616-1391-430c-af1b-7beb42b4dfd8)

When it's done updating it shows installed is now 1.0.9

![Image](https://github.com/user-attachments/assets/ac5eee9a-3d89-474e-ab01-341594a23ca2)

Going back to HACS it shows 1.0.9 installed again

![Image](https://github.com/user-attachments/assets/1e6b7e4f-8e72-425f-b8ec-9b0a29cb8781)

**Comment by Nerwyn** [comment]
1.0.9 is the latest version because 1.0.10-beta is a beta. Just don't downgrade to 1.0.9.

**Comment by xvlw** [comment]
Then I guess the view tabs aren't fixed for me when using 1.0.10-beta

Version

![Image](https://github.com/user-attachments/assets/0e554e77-8915-4fb6-8d37-6f425cbbe5d6)

View Tabs

![Image](https://github.com/user-attachments/assets/d6ae3a74-8307-4801-82d3-2257b4da743a)

**Comment by Nerwyn** [comment]
Did you thoroughly clear cache?

**Comment by xvlw** [comment]
I did, and did it again as well as hard refresh (Firefox 138.0.1)

Here is a screenshot showing the sidebar with the cookies cleared and all the dashboards still showing

![Image](https://github.com/user-attachments/assets/86700f02-12b3-43d0-be4f-aa0927b98b19)

it's also at the top on mobile (android) after clearing the front end cache through the settings menu

**Comment by nethershaw** [comment]
@xvlw The same thing happened to me a moment ago, but I double checked everything and realized that HACS confused me a bit. Choosing the betas when redownloading the theme and the utilities was sufficient to install them both; it's important that the "Downloaded version" column names the beta versions.

At that time, though, the Status column will say "pending update" and the Settings app will show a notification badge suggesting that update -- but if you follow those breadcrumbs and do that, **HA will actually downgrade the addons back to the latest stable.** Make sure you didn't do the same two-step mistake I did.

**Comment by Nerwyn** [comment]
If you open the Material You Utilities configuration panel, it'll show the module and theme versions in the top right. You can also open sources using browser dev tools and search the module code for references to `sl-tab` (the new tabs used by Home Assistant` and `paper-tab` (the old obsolete tabs used before 2025.5.0). There should only be references to the former.

**Comment by miniminne** [comment]
Can confirm applying both betas (and ignoring the "Update" prompt from HACS) seems to fix the issues! 

![Image](https://github.com/user-attachments/assets/eb9904d7-42f3-4f1f-b22d-0367aa6cb0f6)

**Comment by nethershaw** [comment]
@Nerwyn Thank you for being so on the ball -- I had been working on my HA instance all afternoon and thought I'd broken something!

**Comment by xvlw** [comment]
Yep that's the exact loop i'm stuck in. However I can't get the theme into the same state as the utilities. I even tried removing the theme, downloading 4.0.4 then redownloading the beta but not installing it. It shows the beta in the download version column but also shows it as installed and not pending like Utilities is. Also tried just straight removing the theme and downloading beta, doesn't work

![Image](https://github.com/user-attachments/assets/26300a53-2891-43ea-a9a4-75b46dd1178b)

What's odd is that when im on version 4.0.4 it shows there is beta update indicating that the beta is higher (causing the pending update status) but for Utilities it thinks 1.0.9 is the highest version and the beta is below it. 

![Image](https://github.com/user-attachments/assets/aaec7655-499e-40e1-a966-327e26a3bba5)

Here is the module and Theme from the panel

![Image](https://github.com/user-attachments/assets/d118e396-7cda-4a4a-b662-69cefcd0fd16)

Either way, i'll just wait for the full release since my HACS / update loop seems to be borked

**Comment by Nerwyn** [comment]
Fixed in theme [4.0.5](https://github.com/Nerwyn/material-you-theme/releases/tag/4.0.5) and module [1.0.10](https://github.com/Nerwyn/material-you-utilities/releases/tag/1.0.10).

**Comment by MathisP75** [comment]
@xvlw I had to to "clear storage" on mobile for it to work.

**Comment by Nerwyn** [comment]
That would be your cache not clearing properly. Try updating the URLs in configuration.yaml to use the `hacsfiles` endpoint instead of `config/www/community` like the README has been updated to say. That should help with caching issues.

**Comment by Ascathon** [comment]
Minor difference I still see is the tabs on the bottom now spreading from left to right. I believe before they were somewhat centered?

![Image](https://github.com/user-attachments/assets/8fd53fe0-5d7d-42a5-9be8-09a9066633a9)

![Image](https://github.com/user-attachments/assets/0ef5cc63-408b-4759-ae9e-4d39c44d0aa7)

**Comment by D3SOX** [comment]
I noticed the navigation buttons are now a sqaure instead of a rectangle

![Image](https://github.com/user-attachments/assets/82935336-f35b-4487-a3c5-d9cf81d05c8e)

**Comment by valentinfrlch** [comment]
> I noticed the navigation buttons are now a sqaure instead of a rectangle
> 
> ![Image](https://github.com/user-attachments/assets/82935336-f35b-4487-a3c5-d9cf81d05c8e)

I don't think this is related to this issue. Have you reloaded the cache? Is "Style Upgrades" enabled in Material You Utilities?

**Comment by D3SOX** [comment]
Yes, Style Upgrades are enabled and definitely working because the toggle switches look different when it's off.
I already tried reinstalling and clearing caches, restarting fully etc
And it didn't happen before the update

**Comment by Nerwyn** [comment]
> Minor difference I still see is the tabs on the bottom now spreading from left to right. I believe before they were somewhat centered?

Good catch, fixed in 1.0.11.

> I noticed the navigation buttons are now a sqaure instead of a rectangle

That was caused by 2025.5.0 but should be fixed in 1.0.10+. If you're still seeing the square then it's a caching issue. A different user did a great writeup on ways to clear sticky cache issues for a different project of mine [here](https://github.com/Nerwyn/custom-card-features/issues/110#issuecomment-2833550170).

**Comment by Nerwyn** [comment]
The frontend resources UI list doesn't matter. Those modules load too slow for the style changes to apply. What matters is the setup done in `configuration.yaml` for frontend extra module URL and custom panel. Those should use `/hacsfiles/material-you-utilities/material-you-utilities.min.js`.

**Comment by D3SOX** [comment]
That also loads for me in both browser windows and I already have it configured like that

![Image](https://github.com/user-attachments/assets/f55101e6-d2a3-4edb-9079-6dfa2fe1abcd)

**Comment by Nerwyn** [comment]
Were you on that beta version that only fixed the navigation bar? If the navigation bar is fixed but the sidebar isn't then it means that beta fix is still stuck in cache. Updating to the latest patch version (1.0.13 at time of writing) could help push the 1.0.10 beta out of cache.

**Comment by D3SOX** [comment]
Updated to 2025.5.1 and it somehow fixed it

**Comment by jecabe** [comment]
I don’t understand what I might be doing wrong, but with the latest version of Home Assistant and the latest version of the Material You theme, it’s still not displaying correctly. The navigation bar with the dashboards doesn’t appear, and my username is shown in a strange way. Also, depending on the selected theme, the dashboard icons stop working.

![Image](https://github.com/user-attachments/assets/4499861f-b16d-455b-986c-1d3b46e35715)

![Image](https://github.com/user-attachments/assets/bdf44a8b-6cb8-47c1-a058-8fcc5f445f5a)

I’ve tried clearing the cache in both Firefox and Chrome with no success. I also tried from the Android app after clearing its cache, but the issue persists. I even installed a fresh Home Assistant instance on Proxmox to check if something was broken in my current HAOS setup, but the theme still doesn’t work properly there with the latest versions.

Is there anything else I need to do or configure to make the theme work correctly?

**Comment by ZOXSOCKS** [comment]
(thanks for the redirect) 

I've made sure to update everything (even removing the utilities, clearing cache, reinstalling, clearing again) and its still showing as 
 version 1.0.5 and I'm still experiencing the same symptoms as above on both desktop and mobile.

**Comment by catsimple** [comment]
> (thanks for the redirect)
> 
> I've made sure to update everything (even removing the utilities, clearing cache, reinstalling, clearing again) and its still showing as version 1.0.5 and I'm still experiencing the same symptoms as above on both desktop and mobile.

In configuaration.yaml,
    - /**hacsfiles**/material-you-utilities/material-you-utilities.min.js


instead of - /**local/community**/ha-material-you-utilities/material-you-utilities.min.js

**Comment by Oddiesea** [comment]
I'm still having the same issue as @ZOXSOCKS too (theme up to date 4.0.6, but stuck at 1.0.8 in utils). Have been trying for the last few days, using direct ip for the server, purging cloudflare cache, deleting/reinstalling from hacs a number of times, clearing frontend cache, using new browsers/networks. If anyone has any more ideas to resolve the sticky cache please let me know.

Using /hacsfiles/material-you-utilities/material-you-utilities.min.js in the config also

**Comment by ZOXSOCKS** [comment]
> In configuaration.yaml, - /**hacsfiles**/material-you-utilities/material-you-utilities.min.js
> 
> instead of - /**local/community**/ha-material-you-utilities/material-you-utilities.min.js

This hasn't changed anything unfortunately. Still stuck on 1.0.5.

**Comment by Nerwyn** [comment]
I've created [a discussion thread](https://github.com/Nerwyn/material-you-utilities/discussions/12) with common troubleshooting steps/fixes for configuration and stuck cache. Feel free to continue the discussion and add more possible solutions there. I'd like to centralize the troubleshooting discussion there so we can point users to one place for help.

**Comment by antgustech** [comment]
Broken for me as well. The profile looks weird. Dsshboard buttons are on top and not working when tapped. I have tried clearing frontend cache.

![Image](https://github.com/user-attachments/assets/8bb26ec2-35e3-48dc-9ae2-e8eb025a856a)
![Image](https://github.com/user-attachments/assets/5c5633fe-bb37-47f6-ac00-0405c9978260)

**Comment by Mustard4868** [comment]
Hi, I'm still experiencing this issue on the latest version.
I deleted the material rounded theme which solved the issue with the profile picture for me.
However the navigation bar is still in the wrong place on mobile devices.
